// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groups.proto

package groups

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateGroupRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Parent:
	//	*CreateGroupRequest_FirstId
	//	*CreateGroupRequest_SecondId
	//	*CreateGroupRequest_ThirdId
	Parent isCreateGroupRequest_Parent `protobuf_oneof:"parent"`
}

func (m *CreateGroupRequest) Reset()                    { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()               {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isCreateGroupRequest_Parent interface{ isCreateGroupRequest_Parent() }

type CreateGroupRequest_FirstId struct {
	FirstId string `protobuf:"bytes,2,opt,name=first_id,json=firstId,oneof"`
}
type CreateGroupRequest_SecondId struct {
	SecondId string `protobuf:"bytes,3,opt,name=second_id,json=secondId,oneof"`
}
type CreateGroupRequest_ThirdId struct {
	ThirdId string `protobuf:"bytes,4,opt,name=third_id,json=thirdId,oneof"`
}

func (*CreateGroupRequest_FirstId) isCreateGroupRequest_Parent()  {}
func (*CreateGroupRequest_SecondId) isCreateGroupRequest_Parent() {}
func (*CreateGroupRequest_ThirdId) isCreateGroupRequest_Parent()  {}

func (m *CreateGroupRequest) GetParent() isCreateGroupRequest_Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *CreateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGroupRequest) GetFirstId() string {
	if x, ok := m.GetParent().(*CreateGroupRequest_FirstId); ok {
		return x.FirstId
	}
	return ""
}

func (m *CreateGroupRequest) GetSecondId() string {
	if x, ok := m.GetParent().(*CreateGroupRequest_SecondId); ok {
		return x.SecondId
	}
	return ""
}

func (m *CreateGroupRequest) GetThirdId() string {
	if x, ok := m.GetParent().(*CreateGroupRequest_ThirdId); ok {
		return x.ThirdId
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateGroupRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateGroupRequest_OneofMarshaler, _CreateGroupRequest_OneofUnmarshaler, _CreateGroupRequest_OneofSizer, []interface{}{
		(*CreateGroupRequest_FirstId)(nil),
		(*CreateGroupRequest_SecondId)(nil),
		(*CreateGroupRequest_ThirdId)(nil),
	}
}

func _CreateGroupRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateGroupRequest)
	// parent
	switch x := m.Parent.(type) {
	case *CreateGroupRequest_FirstId:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.FirstId)
	case *CreateGroupRequest_SecondId:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.SecondId)
	case *CreateGroupRequest_ThirdId:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ThirdId)
	case nil:
	default:
		return fmt.Errorf("CreateGroupRequest.Parent has unexpected type %T", x)
	}
	return nil
}

func _CreateGroupRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateGroupRequest)
	switch tag {
	case 2: // parent.first_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Parent = &CreateGroupRequest_FirstId{x}
		return true, err
	case 3: // parent.second_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Parent = &CreateGroupRequest_SecondId{x}
		return true, err
	case 4: // parent.third_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Parent = &CreateGroupRequest_ThirdId{x}
		return true, err
	default:
		return false, nil
	}
}

func _CreateGroupRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateGroupRequest)
	// parent
	switch x := m.Parent.(type) {
	case *CreateGroupRequest_FirstId:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.FirstId)))
		n += len(x.FirstId)
	case *CreateGroupRequest_SecondId:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.SecondId)))
		n += len(x.SecondId)
	case *CreateGroupRequest_ThirdId:
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.ThirdId)))
		n += len(x.ThirdId)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Group struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Parent:
	//	*Group_FirstId
	//	*Group_SecondId
	//	*Group_ThirdId
	Parent    isGroup_Parent             `protobuf_oneof:"parent"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type isGroup_Parent interface{ isGroup_Parent() }

type Group_FirstId struct {
	FirstId string `protobuf:"bytes,3,opt,name=first_id,json=firstId,oneof"`
}
type Group_SecondId struct {
	SecondId string `protobuf:"bytes,4,opt,name=second_id,json=secondId,oneof"`
}
type Group_ThirdId struct {
	ThirdId string `protobuf:"bytes,5,opt,name=third_id,json=thirdId,oneof"`
}

func (*Group_FirstId) isGroup_Parent()  {}
func (*Group_SecondId) isGroup_Parent() {}
func (*Group_ThirdId) isGroup_Parent()  {}

func (m *Group) GetParent() isGroup_Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetFirstId() string {
	if x, ok := m.GetParent().(*Group_FirstId); ok {
		return x.FirstId
	}
	return ""
}

func (m *Group) GetSecondId() string {
	if x, ok := m.GetParent().(*Group_SecondId); ok {
		return x.SecondId
	}
	return ""
}

func (m *Group) GetThirdId() string {
	if x, ok := m.GetParent().(*Group_ThirdId); ok {
		return x.ThirdId
	}
	return ""
}

func (m *Group) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Group) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Group) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Group_OneofMarshaler, _Group_OneofUnmarshaler, _Group_OneofSizer, []interface{}{
		(*Group_FirstId)(nil),
		(*Group_SecondId)(nil),
		(*Group_ThirdId)(nil),
	}
}

func _Group_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Group)
	// parent
	switch x := m.Parent.(type) {
	case *Group_FirstId:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.FirstId)
	case *Group_SecondId:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.SecondId)
	case *Group_ThirdId:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ThirdId)
	case nil:
	default:
		return fmt.Errorf("Group.Parent has unexpected type %T", x)
	}
	return nil
}

func _Group_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Group)
	switch tag {
	case 3: // parent.first_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Parent = &Group_FirstId{x}
		return true, err
	case 4: // parent.second_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Parent = &Group_SecondId{x}
		return true, err
	case 5: // parent.third_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Parent = &Group_ThirdId{x}
		return true, err
	default:
		return false, nil
	}
}

func _Group_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Group)
	// parent
	switch x := m.Parent.(type) {
	case *Group_FirstId:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.FirstId)))
		n += len(x.FirstId)
	case *Group_SecondId:
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.SecondId)))
		n += len(x.SecondId)
	case *Group_ThirdId:
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.ThirdId)))
		n += len(x.ThirdId)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*CreateGroupRequest)(nil), "groups.CreateGroupRequest")
	proto.RegisterType((*Group)(nil), "groups.Group")
}

func init() { proto.RegisterFile("groups.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x89, 0x69, 0xd3, 0xc4, 0x20, 0x06, 0x4f, 0x51, 0x2a, 0xd4, 0xaa, 0x08, 0xa9, 0x4b,
	0x13, 0x09, 0x24, 0x24, 0xc6, 0x96, 0x01, 0xb2, 0x46, 0x0c, 0x6c, 0x95, 0x13, 0xbb, 0xa9, 0x45,
	0x13, 0x07, 0xfb, 0x42, 0x5f, 0x80, 0x37, 0xe1, 0xc1, 0x90, 0x78, 0x12, 0x14, 0x27, 0x69, 0xa3,
	0x2e, 0x6c, 0xe7, 0xfb, 0xff, 0xff, 0xfc, 0xe9, 0x0e, 0x5f, 0x66, 0x4a, 0x56, 0xa5, 0x0e, 0x4a,
	0x25, 0x41, 0x12, 0xbb, 0x79, 0xf9, 0x93, 0x4c, 0xca, 0x6c, 0xc7, 0x43, 0xd3, 0x4d, 0xaa, 0x4d,
	0x08, 0x22, 0xe7, 0x1a, 0x68, 0x5e, 0x36, 0x46, 0xff, 0x21, 0x13, 0xb0, 0xad, 0x92, 0x20, 0x95,
	0x79, 0x98, 0xef, 0x05, 0xbc, 0xcb, 0x7d, 0x98, 0xc9, 0x85, 0x11, 0x17, 0x9f, 0x74, 0x27, 0x18,
	0x05, 0xa9, 0x74, 0x78, 0x28, 0x9b, 0xdc, 0xec, 0xdb, 0xc2, 0xe4, 0x49, 0x71, 0x0a, 0xfc, 0xb9,
	0xfe, 0x29, 0xe6, 0x1f, 0x15, 0xd7, 0x40, 0x08, 0x1e, 0x14, 0x34, 0xe7, 0x9e, 0x35, 0xb5, 0xe6,
	0x6e, 0x6c, 0x6a, 0x72, 0x83, 0x9d, 0x8d, 0x50, 0x1a, 0xd6, 0x82, 0x79, 0xa8, 0xee, 0xaf, 0xec,
	0xdf, 0x9f, 0x09, 0x7a, 0xb3, 0x5e, 0xce, 0xe2, 0x91, 0x51, 0x22, 0x46, 0x6e, 0xb1, 0xab, 0x79,
	0x2a, 0x0b, 0x56, 0xbb, 0xce, 0x4f, 0x5c, 0x4e, 0x23, 0x45, 0xac, 0x9e, 0x05, 0x5b, 0xa1, 0x8c,
	0x6b, 0x70, 0x3a, 0xcb, 0x28, 0x11, 0x5b, 0x39, 0xd8, 0x2e, 0xa9, 0xe2, 0x05, 0xcc, 0xbe, 0x10,
	0x1e, 0x1a, 0x3e, 0x72, 0x85, 0x91, 0x60, 0x2d, 0x16, 0x12, 0xec, 0x00, 0x8a, 0x7a, 0xa0, 0xe3,
	0x1e, 0xa8, 0x41, 0xe8, 0x03, 0x5e, 0xf7, 0x01, 0x07, 0xad, 0x7a, 0x04, 0x1b, 0xf7, 0xc0, 0x86,
	0x5d, 0xb6, 0x05, 0x22, 0x8f, 0x18, 0xa7, 0x66, 0x57, 0x6c, 0x4d, 0xc1, 0xb3, 0xa7, 0xd6, 0xfc,
	0xe2, 0xce, 0x0f, 0x9a, 0xd3, 0x04, 0xdd, 0x69, 0x82, 0xd7, 0xee, 0x34, 0xb1, 0xdb, 0xba, 0x97,
	0x50, 0x47, 0xab, 0x92, 0x75, 0xd1, 0xd1, 0xff, 0xd1, 0xd6, 0xbd, 0x84, 0xe3, 0x1a, 0x12, 0xdb,
	0x18, 0xef, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x31, 0x6d, 0xdb, 0xcc, 0x24, 0x02, 0x00, 0x00,
}
